name : Open Resources
brand : Open Resources
description : An open source taxonomy of resources.
keyword :
url : http://openresources.github.io
email : info@folklabs.com
twitter : folklabs
github : openresources
author : Folk Labs
analytics :
year : 2015
markdown : kramdown

exclude:
- node_modules
